
### Create a new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"test1@test.com",
    "password":"123456"
}
### sign in user
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"test1@test.com",
    "password":"123456"
}

### get currently signed user
GET  http://localhost:3000/auth/whoami
Content-Type: application/json

### sign out
POST  http://localhost:3000/auth/signOut
Content-Type: application/json

### find particular user
GET  http://localhost:3000/auth/2
Content-Type: application/json

### find all users
GET  http://localhost:3000/auth
Content-Type: application/json

### Delete particular user
DELETE  http://localhost:3000/auth/1
Content-Type: application/json


### Update particular user
PATCH   http://localhost:3000/auth/2
Content-Type: application/json

{
    "password":"phong"
}

